#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDiem.DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLDiem")]
	public partial class QLdiemDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDangNhap(DangNhap instance);
    partial void UpdateDangNhap(DangNhap instance);
    partial void DeleteDangNhap(DangNhap instance);
    partial void InsertHocKy(HocKy instance);
    partial void UpdateHocKy(HocKy instance);
    partial void DeleteHocKy(HocKy instance);
    partial void InsertLop(Lop instance);
    partial void UpdateLop(Lop instance);
    partial void DeleteLop(Lop instance);
    partial void InsertMonHP(MonHP instance);
    partial void UpdateMonHP(MonHP instance);
    partial void DeleteMonHP(MonHP instance);
    partial void InsertSinhVien(SinhVien instance);
    partial void UpdateSinhVien(SinhVien instance);
    partial void DeleteSinhVien(SinhVien instance);
    #endregion
		
		public QLdiemDataContext() : 
				base(global::QLDiem.Properties.Settings.Default.QLDiemConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLdiemDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLdiemDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLdiemDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLdiemDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ThongTin> ThongTins
		{
			get
			{
				return this.GetTable<ThongTin>();
			}
		}
		
		public System.Data.Linq.Table<DangNhap> DangNhaps
		{
			get
			{
				return this.GetTable<DangNhap>();
			}
		}
		
		public System.Data.Linq.Table<DiemHP> DiemHPs
		{
			get
			{
				return this.GetTable<DiemHP>();
			}
		}
		
		public System.Data.Linq.Table<HocKy> HocKies
		{
			get
			{
				return this.GetTable<HocKy>();
			}
		}
		
		public System.Data.Linq.Table<Lop> Lops
		{
			get
			{
				return this.GetTable<Lop>();
			}
		}
		
		public System.Data.Linq.Table<MonHP> MonHPs
		{
			get
			{
				return this.GetTable<MonHP>();
			}
		}
		
		public System.Data.Linq.Table<SinhVien> SinhViens
		{
			get
			{
				return this.GetTable<SinhVien>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BangDiemHP")]
		public ISingleResult<BangDiemHPResult> BangDiemHP([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string maLop, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string maMon)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maLop, maMon);
			return ((ISingleResult<BangDiemHPResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ThongTin_Update")]
		public int ThongTin_Update([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string tinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string donViChuQuan, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string tenTruong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string khoaHoc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string nganhHoc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string chuyenNganh)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tinh, donViChuQuan, tenTruong, khoaHoc, nganhHoc, chuyenNganh);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DangNhap_Delete")]
		public int DangNhap_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string userName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userName);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DangNhap_Insert")]
		public int DangNhap_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string userName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string passWord, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Quyen", DbType="NVarChar(50)")] string quyen)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userName, passWord, quyen);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DangNhap_SelectAll")]
		public ISingleResult<DangNhap_SelectAllResult> DangNhap_SelectAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<DangNhap_SelectAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DangNhap_SelectQuyen")]
		public ISingleResult<DangNhap_SelectQuyenResult> DangNhap_SelectQuyen([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Quyen", DbType="NVarChar(50)")] string quyen)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), quyen);
			return ((ISingleResult<DangNhap_SelectQuyenResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DangNhap_Update")]
		public int DangNhap_Update([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string userName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string passWord, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Quyen", DbType="NVarChar(50)")] string quyen)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userName, passWord, quyen);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DiemHP_Insert")]
		public int DiemHP_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string maMon, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string maSV)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maMon, maSV);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DiemHP_Search")]
		public ISingleResult<DiemHP_SearchResult> DiemHP_Search([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string maMon, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string maSV)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maMon, maSV);
			return ((ISingleResult<DiemHP_SearchResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DiemHP_UpdateLan1")]
		public int DiemHP_UpdateLan1([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> diemLan1, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string maMon, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string maSV)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), diemLan1, maMon, maSV);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DiemHP_UpdateLan2")]
		public int DiemHP_UpdateLan2([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> diemLan2, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string maMon, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string maSV)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), diemLan2, maMon, maSV);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.HocKy_Delete")]
		public int HocKy_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string maHK)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maHK);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.HocKy_Insert")]
		public int HocKy_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string maHK, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string tenHK)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maHK, tenHK);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.HocKy_SelectAll")]
		public ISingleResult<HocKy_SelectAllResult> HocKy_SelectAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<HocKy_SelectAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.HocKy_Update")]
		public int HocKy_Update([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string maHK, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string tenHK)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maHK, tenHK);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Lops_Delete")]
		public int Lops_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string maLop)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maLop);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Lops_Insert")]
		public int Lops_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string maLop, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string tenLop)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maLop, tenLop);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Lops_SelectAll")]
		public ISingleResult<Lops_SelectAllResult> Lops_SelectAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Lops_SelectAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Lops_Update")]
		public int Lops_Update([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string maLop, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string tenLop)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maLop, tenLop);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MonHP_Delete")]
		public int MonHP_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string maMon)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maMon);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MonHP_Insert")]
		public int MonHP_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string maMon, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string tenMon, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string soTinChi, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string maHK)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maMon, tenMon, soTinChi, maHK);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MonHP_SelectAll")]
		public ISingleResult<MonHP_SelectAllResult> MonHP_SelectAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<MonHP_SelectAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MonHP_SelectMaHK")]
		public ISingleResult<MonHP_SelectMaHKResult> MonHP_SelectMaHK([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string maHK)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maHK);
			return ((ISingleResult<MonHP_SelectMaHKResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MonHP_Update")]
		public int MonHP_Update([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string maMon, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string tenMon, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string soTinChi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maMon, tenMon, soTinChi);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SinhVien_Delete")]
		public int SinhVien_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string maSV)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maSV);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SinhVien_Insert")]
		public int SinhVien_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string maSV, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string hoTen, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> ngaySinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string gioiTinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string noiSinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string danToc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string maLop)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maSV, hoTen, ngaySinh, gioiTinh, noiSinh, danToc, maLop);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SinhVien_Search")]
		public ISingleResult<SinhVien_SearchResult> SinhVien_Search([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string hoTen, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string maLop)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), hoTen, maLop);
			return ((ISingleResult<SinhVien_SearchResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SinhVien_SelectAll")]
		public ISingleResult<SinhVien_SelectAllResult> SinhVien_SelectAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SinhVien_SelectAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SinhVien_SelectID")]
		public ISingleResult<SinhVien_SelectIDResult> SinhVien_SelectID([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string maSV)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maSV);
			return ((ISingleResult<SinhVien_SelectIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SinhVien_SelectMaLop")]
		public ISingleResult<SinhVien_SelectMaLopResult> SinhVien_SelectMaLop([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string maLop)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maLop);
			return ((ISingleResult<SinhVien_SelectMaLopResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SinhVien_Update")]
		public int SinhVien_Update([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string maSV, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string hoTen, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> ngaySinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string gioiTinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string noiSinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string danToc)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maSV, hoTen, ngaySinh, gioiTinh, noiSinh, danToc);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ThongTin_SelectAll")]
		public ISingleResult<ThongTin_SelectAllResult> ThongTin_SelectAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ThongTin_SelectAllResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThongTin")]
	public partial class ThongTin
	{
		
		private string _tinh;
		
		private string _donViChuQuan;
		
		private string _tenTruong;
		
		private string _khoaHoc;
		
		private string _nganhHoc;
		
		private string _chuyenNganh;
		
		public ThongTin()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tinh", DbType="NVarChar(50)")]
		public string tinh
		{
			get
			{
				return this._tinh;
			}
			set
			{
				if ((this._tinh != value))
				{
					this._tinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_donViChuQuan", DbType="NVarChar(100)")]
		public string donViChuQuan
		{
			get
			{
				return this._donViChuQuan;
			}
			set
			{
				if ((this._donViChuQuan != value))
				{
					this._donViChuQuan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenTruong", DbType="NVarChar(100)")]
		public string tenTruong
		{
			get
			{
				return this._tenTruong;
			}
			set
			{
				if ((this._tenTruong != value))
				{
					this._tenTruong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khoaHoc", DbType="NVarChar(100)")]
		public string khoaHoc
		{
			get
			{
				return this._khoaHoc;
			}
			set
			{
				if ((this._khoaHoc != value))
				{
					this._khoaHoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nganhHoc", DbType="NVarChar(100)")]
		public string nganhHoc
		{
			get
			{
				return this._nganhHoc;
			}
			set
			{
				if ((this._nganhHoc != value))
				{
					this._nganhHoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chuyenNganh", DbType="NVarChar(100)")]
		public string chuyenNganh
		{
			get
			{
				return this._chuyenNganh;
			}
			set
			{
				if ((this._chuyenNganh != value))
				{
					this._chuyenNganh = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DangNhap")]
	public partial class DangNhap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _userName;
		
		private string _passWord;
		
		private string _Quyen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuserNameChanging(string value);
    partial void OnuserNameChanged();
    partial void OnpassWordChanging(string value);
    partial void OnpassWordChanged();
    partial void OnQuyenChanging(string value);
    partial void OnQuyenChanged();
    #endregion
		
		public DangNhap()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userName", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string userName
		{
			get
			{
				return this._userName;
			}
			set
			{
				if ((this._userName != value))
				{
					this.OnuserNameChanging(value);
					this.SendPropertyChanging();
					this._userName = value;
					this.SendPropertyChanged("userName");
					this.OnuserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passWord", DbType="NVarChar(100)")]
		public string passWord
		{
			get
			{
				return this._passWord;
			}
			set
			{
				if ((this._passWord != value))
				{
					this.OnpassWordChanging(value);
					this.SendPropertyChanging();
					this._passWord = value;
					this.SendPropertyChanged("passWord");
					this.OnpassWordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quyen", DbType="NVarChar(50)")]
		public string Quyen
		{
			get
			{
				return this._Quyen;
			}
			set
			{
				if ((this._Quyen != value))
				{
					this.OnQuyenChanging(value);
					this.SendPropertyChanging();
					this._Quyen = value;
					this.SendPropertyChanged("Quyen");
					this.OnQuyenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DiemHP")]
	public partial class DiemHP
	{
		
		private string _maSV;
		
		private string _maMon;
		
		private System.Nullable<double> _diemLan1;
		
		private System.Nullable<double> _diemLan2;
		
		public DiemHP()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maSV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maSV
		{
			get
			{
				return this._maSV;
			}
			set
			{
				if ((this._maSV != value))
				{
					this._maSV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maMon", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maMon
		{
			get
			{
				return this._maMon;
			}
			set
			{
				if ((this._maMon != value))
				{
					this._maMon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diemLan1", DbType="Float")]
		public System.Nullable<double> diemLan1
		{
			get
			{
				return this._diemLan1;
			}
			set
			{
				if ((this._diemLan1 != value))
				{
					this._diemLan1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diemLan2", DbType="Float")]
		public System.Nullable<double> diemLan2
		{
			get
			{
				return this._diemLan2;
			}
			set
			{
				if ((this._diemLan2 != value))
				{
					this._diemLan2 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HocKy")]
	public partial class HocKy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maHK;
		
		private string _tenHK;
		
		private EntitySet<MonHP> _MonHPs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaHKChanging(string value);
    partial void OnmaHKChanged();
    partial void OntenHKChanging(string value);
    partial void OntenHKChanged();
    #endregion
		
		public HocKy()
		{
			this._MonHPs = new EntitySet<MonHP>(new Action<MonHP>(this.attach_MonHPs), new Action<MonHP>(this.detach_MonHPs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHK", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maHK
		{
			get
			{
				return this._maHK;
			}
			set
			{
				if ((this._maHK != value))
				{
					this.OnmaHKChanging(value);
					this.SendPropertyChanging();
					this._maHK = value;
					this.SendPropertyChanged("maHK");
					this.OnmaHKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenHK", DbType="NVarChar(100)")]
		public string tenHK
		{
			get
			{
				return this._tenHK;
			}
			set
			{
				if ((this._tenHK != value))
				{
					this.OntenHKChanging(value);
					this.SendPropertyChanging();
					this._tenHK = value;
					this.SendPropertyChanged("tenHK");
					this.OntenHKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HocKy_MonHP", Storage="_MonHPs", ThisKey="maHK", OtherKey="maHK")]
		public EntitySet<MonHP> MonHPs
		{
			get
			{
				return this._MonHPs;
			}
			set
			{
				this._MonHPs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MonHPs(MonHP entity)
		{
			this.SendPropertyChanging();
			entity.HocKy = this;
		}
		
		private void detach_MonHPs(MonHP entity)
		{
			this.SendPropertyChanging();
			entity.HocKy = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Lops")]
	public partial class Lop : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maLop;
		
		private string _tenLop;
		
		private EntitySet<SinhVien> _SinhViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaLopChanging(string value);
    partial void OnmaLopChanged();
    partial void OntenLopChanging(string value);
    partial void OntenLopChanged();
    #endregion
		
		public Lop()
		{
			this._SinhViens = new EntitySet<SinhVien>(new Action<SinhVien>(this.attach_SinhViens), new Action<SinhVien>(this.detach_SinhViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLop", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maLop
		{
			get
			{
				return this._maLop;
			}
			set
			{
				if ((this._maLop != value))
				{
					this.OnmaLopChanging(value);
					this.SendPropertyChanging();
					this._maLop = value;
					this.SendPropertyChanged("maLop");
					this.OnmaLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenLop", DbType="NVarChar(100)")]
		public string tenLop
		{
			get
			{
				return this._tenLop;
			}
			set
			{
				if ((this._tenLop != value))
				{
					this.OntenLopChanging(value);
					this.SendPropertyChanging();
					this._tenLop = value;
					this.SendPropertyChanged("tenLop");
					this.OntenLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Lop_SinhVien", Storage="_SinhViens", ThisKey="maLop", OtherKey="maLop")]
		public EntitySet<SinhVien> SinhViens
		{
			get
			{
				return this._SinhViens;
			}
			set
			{
				this._SinhViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SinhViens(SinhVien entity)
		{
			this.SendPropertyChanging();
			entity.Lop = this;
		}
		
		private void detach_SinhViens(SinhVien entity)
		{
			this.SendPropertyChanging();
			entity.Lop = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MonHP")]
	public partial class MonHP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maMon;
		
		private string _tenMon;
		
		private string _soTinChi;
		
		private string _maHK;
		
		private EntityRef<HocKy> _HocKy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaMonChanging(string value);
    partial void OnmaMonChanged();
    partial void OntenMonChanging(string value);
    partial void OntenMonChanged();
    partial void OnsoTinChiChanging(string value);
    partial void OnsoTinChiChanged();
    partial void OnmaHKChanging(string value);
    partial void OnmaHKChanged();
    #endregion
		
		public MonHP()
		{
			this._HocKy = default(EntityRef<HocKy>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maMon", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maMon
		{
			get
			{
				return this._maMon;
			}
			set
			{
				if ((this._maMon != value))
				{
					this.OnmaMonChanging(value);
					this.SendPropertyChanging();
					this._maMon = value;
					this.SendPropertyChanged("maMon");
					this.OnmaMonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenMon", DbType="NVarChar(100)")]
		public string tenMon
		{
			get
			{
				return this._tenMon;
			}
			set
			{
				if ((this._tenMon != value))
				{
					this.OntenMonChanging(value);
					this.SendPropertyChanging();
					this._tenMon = value;
					this.SendPropertyChanged("tenMon");
					this.OntenMonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soTinChi", DbType="NVarChar(50)")]
		public string soTinChi
		{
			get
			{
				return this._soTinChi;
			}
			set
			{
				if ((this._soTinChi != value))
				{
					this.OnsoTinChiChanging(value);
					this.SendPropertyChanging();
					this._soTinChi = value;
					this.SendPropertyChanged("soTinChi");
					this.OnsoTinChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHK", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maHK
		{
			get
			{
				return this._maHK;
			}
			set
			{
				if ((this._maHK != value))
				{
					if (this._HocKy.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaHKChanging(value);
					this.SendPropertyChanging();
					this._maHK = value;
					this.SendPropertyChanged("maHK");
					this.OnmaHKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HocKy_MonHP", Storage="_HocKy", ThisKey="maHK", OtherKey="maHK", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public HocKy HocKy
		{
			get
			{
				return this._HocKy.Entity;
			}
			set
			{
				HocKy previousValue = this._HocKy.Entity;
				if (((previousValue != value) 
							|| (this._HocKy.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HocKy.Entity = null;
						previousValue.MonHPs.Remove(this);
					}
					this._HocKy.Entity = value;
					if ((value != null))
					{
						value.MonHPs.Add(this);
						this._maHK = value.maHK;
					}
					else
					{
						this._maHK = default(string);
					}
					this.SendPropertyChanged("HocKy");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SinhVien")]
	public partial class SinhVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maSV;
		
		private string _hoTen;
		
		private System.Nullable<System.DateTime> _ngaySinh;
		
		private string _gioiTinh;
		
		private string _noiSinh;
		
		private string _danToc;
		
		private string _maLop;
		
		private EntityRef<Lop> _Lop;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaSVChanging(string value);
    partial void OnmaSVChanged();
    partial void OnhoTenChanging(string value);
    partial void OnhoTenChanged();
    partial void OnngaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnngaySinhChanged();
    partial void OngioiTinhChanging(string value);
    partial void OngioiTinhChanged();
    partial void OnnoiSinhChanging(string value);
    partial void OnnoiSinhChanged();
    partial void OndanTocChanging(string value);
    partial void OndanTocChanged();
    partial void OnmaLopChanging(string value);
    partial void OnmaLopChanged();
    #endregion
		
		public SinhVien()
		{
			this._Lop = default(EntityRef<Lop>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maSV", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maSV
		{
			get
			{
				return this._maSV;
			}
			set
			{
				if ((this._maSV != value))
				{
					this.OnmaSVChanging(value);
					this.SendPropertyChanging();
					this._maSV = value;
					this.SendPropertyChanged("maSV");
					this.OnmaSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoTen", DbType="NVarChar(100)")]
		public string hoTen
		{
			get
			{
				return this._hoTen;
			}
			set
			{
				if ((this._hoTen != value))
				{
					this.OnhoTenChanging(value);
					this.SendPropertyChanging();
					this._hoTen = value;
					this.SendPropertyChanged("hoTen");
					this.OnhoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> ngaySinh
		{
			get
			{
				return this._ngaySinh;
			}
			set
			{
				if ((this._ngaySinh != value))
				{
					this.OnngaySinhChanging(value);
					this.SendPropertyChanging();
					this._ngaySinh = value;
					this.SendPropertyChanged("ngaySinh");
					this.OnngaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioiTinh", DbType="NVarChar(50)")]
		public string gioiTinh
		{
			get
			{
				return this._gioiTinh;
			}
			set
			{
				if ((this._gioiTinh != value))
				{
					this.OngioiTinhChanging(value);
					this.SendPropertyChanging();
					this._gioiTinh = value;
					this.SendPropertyChanged("gioiTinh");
					this.OngioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noiSinh", DbType="NVarChar(100)")]
		public string noiSinh
		{
			get
			{
				return this._noiSinh;
			}
			set
			{
				if ((this._noiSinh != value))
				{
					this.OnnoiSinhChanging(value);
					this.SendPropertyChanging();
					this._noiSinh = value;
					this.SendPropertyChanged("noiSinh");
					this.OnnoiSinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_danToc", DbType="NVarChar(100)")]
		public string danToc
		{
			get
			{
				return this._danToc;
			}
			set
			{
				if ((this._danToc != value))
				{
					this.OndanTocChanging(value);
					this.SendPropertyChanging();
					this._danToc = value;
					this.SendPropertyChanged("danToc");
					this.OndanTocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLop", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maLop
		{
			get
			{
				return this._maLop;
			}
			set
			{
				if ((this._maLop != value))
				{
					if (this._Lop.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaLopChanging(value);
					this.SendPropertyChanging();
					this._maLop = value;
					this.SendPropertyChanged("maLop");
					this.OnmaLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Lop_SinhVien", Storage="_Lop", ThisKey="maLop", OtherKey="maLop", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Lop Lop
		{
			get
			{
				return this._Lop.Entity;
			}
			set
			{
				Lop previousValue = this._Lop.Entity;
				if (((previousValue != value) 
							|| (this._Lop.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Lop.Entity = null;
						previousValue.SinhViens.Remove(this);
					}
					this._Lop.Entity = value;
					if ((value != null))
					{
						value.SinhViens.Add(this);
						this._maLop = value.maLop;
					}
					else
					{
						this._maLop = default(string);
					}
					this.SendPropertyChanged("Lop");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class BangDiemHPResult
	{
		
		private string _maSV;
		
		private string _hoTen;
		
		private System.Nullable<System.DateTime> _ngaySinh;
		
		private System.Nullable<double> _diemLan1;
		
		private System.Nullable<double> _diemLan2;
		
		public BangDiemHPResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maSV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maSV
		{
			get
			{
				return this._maSV;
			}
			set
			{
				if ((this._maSV != value))
				{
					this._maSV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoTen", DbType="NVarChar(100)")]
		public string hoTen
		{
			get
			{
				return this._hoTen;
			}
			set
			{
				if ((this._hoTen != value))
				{
					this._hoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> ngaySinh
		{
			get
			{
				return this._ngaySinh;
			}
			set
			{
				if ((this._ngaySinh != value))
				{
					this._ngaySinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diemLan1", DbType="Float")]
		public System.Nullable<double> diemLan1
		{
			get
			{
				return this._diemLan1;
			}
			set
			{
				if ((this._diemLan1 != value))
				{
					this._diemLan1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diemLan2", DbType="Float")]
		public System.Nullable<double> diemLan2
		{
			get
			{
				return this._diemLan2;
			}
			set
			{
				if ((this._diemLan2 != value))
				{
					this._diemLan2 = value;
				}
			}
		}
	}
	
	public partial class DangNhap_SelectAllResult
	{
		
		private string _userName;
		
		private string _passWord;
		
		private string _Quyen;
		
		public DangNhap_SelectAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string userName
		{
			get
			{
				return this._userName;
			}
			set
			{
				if ((this._userName != value))
				{
					this._userName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passWord", DbType="NVarChar(100)")]
		public string passWord
		{
			get
			{
				return this._passWord;
			}
			set
			{
				if ((this._passWord != value))
				{
					this._passWord = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quyen", DbType="NVarChar(50)")]
		public string Quyen
		{
			get
			{
				return this._Quyen;
			}
			set
			{
				if ((this._Quyen != value))
				{
					this._Quyen = value;
				}
			}
		}
	}
	
	public partial class DangNhap_SelectQuyenResult
	{
		
		private string _userName;
		
		private string _passWord;
		
		private string _Quyen;
		
		public DangNhap_SelectQuyenResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string userName
		{
			get
			{
				return this._userName;
			}
			set
			{
				if ((this._userName != value))
				{
					this._userName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passWord", DbType="NVarChar(100)")]
		public string passWord
		{
			get
			{
				return this._passWord;
			}
			set
			{
				if ((this._passWord != value))
				{
					this._passWord = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quyen", DbType="NVarChar(50)")]
		public string Quyen
		{
			get
			{
				return this._Quyen;
			}
			set
			{
				if ((this._Quyen != value))
				{
					this._Quyen = value;
				}
			}
		}
	}
	
	public partial class DiemHP_SearchResult
	{
		
		private string _maSV;
		
		private string _maMon;
		
		private System.Nullable<double> _diemLan1;
		
		private System.Nullable<double> _diemLan2;
		
		public DiemHP_SearchResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maSV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maSV
		{
			get
			{
				return this._maSV;
			}
			set
			{
				if ((this._maSV != value))
				{
					this._maSV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maMon", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maMon
		{
			get
			{
				return this._maMon;
			}
			set
			{
				if ((this._maMon != value))
				{
					this._maMon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diemLan1", DbType="Float")]
		public System.Nullable<double> diemLan1
		{
			get
			{
				return this._diemLan1;
			}
			set
			{
				if ((this._diemLan1 != value))
				{
					this._diemLan1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diemLan2", DbType="Float")]
		public System.Nullable<double> diemLan2
		{
			get
			{
				return this._diemLan2;
			}
			set
			{
				if ((this._diemLan2 != value))
				{
					this._diemLan2 = value;
				}
			}
		}
	}
	
	public partial class HocKy_SelectAllResult
	{
		
		private string _maHK;
		
		private string _tenHK;
		
		public HocKy_SelectAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHK", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maHK
		{
			get
			{
				return this._maHK;
			}
			set
			{
				if ((this._maHK != value))
				{
					this._maHK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenHK", DbType="NVarChar(100)")]
		public string tenHK
		{
			get
			{
				return this._tenHK;
			}
			set
			{
				if ((this._tenHK != value))
				{
					this._tenHK = value;
				}
			}
		}
	}
	
	public partial class Lops_SelectAllResult
	{
		
		private string _maLop;
		
		private string _tenLop;
		
		public Lops_SelectAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLop", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maLop
		{
			get
			{
				return this._maLop;
			}
			set
			{
				if ((this._maLop != value))
				{
					this._maLop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenLop", DbType="NVarChar(100)")]
		public string tenLop
		{
			get
			{
				return this._tenLop;
			}
			set
			{
				if ((this._tenLop != value))
				{
					this._tenLop = value;
				}
			}
		}
	}
	
	public partial class MonHP_SelectAllResult
	{
		
		private string _maMon;
		
		private string _tenMon;
		
		private string _soTinChi;
		
		private string _maHK;
		
		public MonHP_SelectAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maMon", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maMon
		{
			get
			{
				return this._maMon;
			}
			set
			{
				if ((this._maMon != value))
				{
					this._maMon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenMon", DbType="NVarChar(100)")]
		public string tenMon
		{
			get
			{
				return this._tenMon;
			}
			set
			{
				if ((this._tenMon != value))
				{
					this._tenMon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soTinChi", DbType="NVarChar(50)")]
		public string soTinChi
		{
			get
			{
				return this._soTinChi;
			}
			set
			{
				if ((this._soTinChi != value))
				{
					this._soTinChi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHK", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maHK
		{
			get
			{
				return this._maHK;
			}
			set
			{
				if ((this._maHK != value))
				{
					this._maHK = value;
				}
			}
		}
	}
	
	public partial class MonHP_SelectMaHKResult
	{
		
		private string _maMon;
		
		private string _tenMon;
		
		private string _soTinChi;
		
		private string _maHK;
		
		public MonHP_SelectMaHKResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maMon", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maMon
		{
			get
			{
				return this._maMon;
			}
			set
			{
				if ((this._maMon != value))
				{
					this._maMon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenMon", DbType="NVarChar(100)")]
		public string tenMon
		{
			get
			{
				return this._tenMon;
			}
			set
			{
				if ((this._tenMon != value))
				{
					this._tenMon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soTinChi", DbType="NVarChar(50)")]
		public string soTinChi
		{
			get
			{
				return this._soTinChi;
			}
			set
			{
				if ((this._soTinChi != value))
				{
					this._soTinChi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHK", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maHK
		{
			get
			{
				return this._maHK;
			}
			set
			{
				if ((this._maHK != value))
				{
					this._maHK = value;
				}
			}
		}
	}
	
	public partial class SinhVien_SearchResult
	{
		
		private string _maSV;
		
		private string _hoTen;
		
		private System.Nullable<System.DateTime> _ngaySinh;
		
		private string _gioiTinh;
		
		private string _noiSinh;
		
		private string _danToc;
		
		private string _maLop;
		
		public SinhVien_SearchResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maSV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maSV
		{
			get
			{
				return this._maSV;
			}
			set
			{
				if ((this._maSV != value))
				{
					this._maSV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoTen", DbType="NVarChar(100)")]
		public string hoTen
		{
			get
			{
				return this._hoTen;
			}
			set
			{
				if ((this._hoTen != value))
				{
					this._hoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> ngaySinh
		{
			get
			{
				return this._ngaySinh;
			}
			set
			{
				if ((this._ngaySinh != value))
				{
					this._ngaySinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioiTinh", DbType="NVarChar(50)")]
		public string gioiTinh
		{
			get
			{
				return this._gioiTinh;
			}
			set
			{
				if ((this._gioiTinh != value))
				{
					this._gioiTinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noiSinh", DbType="NVarChar(100)")]
		public string noiSinh
		{
			get
			{
				return this._noiSinh;
			}
			set
			{
				if ((this._noiSinh != value))
				{
					this._noiSinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_danToc", DbType="NVarChar(100)")]
		public string danToc
		{
			get
			{
				return this._danToc;
			}
			set
			{
				if ((this._danToc != value))
				{
					this._danToc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLop", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maLop
		{
			get
			{
				return this._maLop;
			}
			set
			{
				if ((this._maLop != value))
				{
					this._maLop = value;
				}
			}
		}
	}
	
	public partial class SinhVien_SelectAllResult
	{
		
		private string _maSV;
		
		private string _hoTen;
		
		private System.Nullable<System.DateTime> _ngaySinh;
		
		private string _gioiTinh;
		
		private string _noiSinh;
		
		private string _danToc;
		
		private string _maLop;
		
		public SinhVien_SelectAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maSV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maSV
		{
			get
			{
				return this._maSV;
			}
			set
			{
				if ((this._maSV != value))
				{
					this._maSV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoTen", DbType="NVarChar(100)")]
		public string hoTen
		{
			get
			{
				return this._hoTen;
			}
			set
			{
				if ((this._hoTen != value))
				{
					this._hoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> ngaySinh
		{
			get
			{
				return this._ngaySinh;
			}
			set
			{
				if ((this._ngaySinh != value))
				{
					this._ngaySinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioiTinh", DbType="NVarChar(50)")]
		public string gioiTinh
		{
			get
			{
				return this._gioiTinh;
			}
			set
			{
				if ((this._gioiTinh != value))
				{
					this._gioiTinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noiSinh", DbType="NVarChar(100)")]
		public string noiSinh
		{
			get
			{
				return this._noiSinh;
			}
			set
			{
				if ((this._noiSinh != value))
				{
					this._noiSinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_danToc", DbType="NVarChar(100)")]
		public string danToc
		{
			get
			{
				return this._danToc;
			}
			set
			{
				if ((this._danToc != value))
				{
					this._danToc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLop", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maLop
		{
			get
			{
				return this._maLop;
			}
			set
			{
				if ((this._maLop != value))
				{
					this._maLop = value;
				}
			}
		}
	}
	
	public partial class SinhVien_SelectIDResult
	{
		
		private string _maSV;
		
		private string _hoTen;
		
		private System.Nullable<System.DateTime> _ngaySinh;
		
		private string _gioiTinh;
		
		private string _noiSinh;
		
		private string _danToc;
		
		private string _maLop;
		
		public SinhVien_SelectIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maSV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maSV
		{
			get
			{
				return this._maSV;
			}
			set
			{
				if ((this._maSV != value))
				{
					this._maSV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoTen", DbType="NVarChar(100)")]
		public string hoTen
		{
			get
			{
				return this._hoTen;
			}
			set
			{
				if ((this._hoTen != value))
				{
					this._hoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> ngaySinh
		{
			get
			{
				return this._ngaySinh;
			}
			set
			{
				if ((this._ngaySinh != value))
				{
					this._ngaySinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioiTinh", DbType="NVarChar(50)")]
		public string gioiTinh
		{
			get
			{
				return this._gioiTinh;
			}
			set
			{
				if ((this._gioiTinh != value))
				{
					this._gioiTinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noiSinh", DbType="NVarChar(100)")]
		public string noiSinh
		{
			get
			{
				return this._noiSinh;
			}
			set
			{
				if ((this._noiSinh != value))
				{
					this._noiSinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_danToc", DbType="NVarChar(100)")]
		public string danToc
		{
			get
			{
				return this._danToc;
			}
			set
			{
				if ((this._danToc != value))
				{
					this._danToc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLop", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maLop
		{
			get
			{
				return this._maLop;
			}
			set
			{
				if ((this._maLop != value))
				{
					this._maLop = value;
				}
			}
		}
	}
	
	public partial class SinhVien_SelectMaLopResult
	{
		
		private string _maSV;
		
		private string _hoTen;
		
		private System.Nullable<System.DateTime> _ngaySinh;
		
		private string _gioiTinh;
		
		private string _noiSinh;
		
		private string _danToc;
		
		private string _maLop;
		
		public SinhVien_SelectMaLopResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maSV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maSV
		{
			get
			{
				return this._maSV;
			}
			set
			{
				if ((this._maSV != value))
				{
					this._maSV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoTen", DbType="NVarChar(100)")]
		public string hoTen
		{
			get
			{
				return this._hoTen;
			}
			set
			{
				if ((this._hoTen != value))
				{
					this._hoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> ngaySinh
		{
			get
			{
				return this._ngaySinh;
			}
			set
			{
				if ((this._ngaySinh != value))
				{
					this._ngaySinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioiTinh", DbType="NVarChar(50)")]
		public string gioiTinh
		{
			get
			{
				return this._gioiTinh;
			}
			set
			{
				if ((this._gioiTinh != value))
				{
					this._gioiTinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noiSinh", DbType="NVarChar(100)")]
		public string noiSinh
		{
			get
			{
				return this._noiSinh;
			}
			set
			{
				if ((this._noiSinh != value))
				{
					this._noiSinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_danToc", DbType="NVarChar(100)")]
		public string danToc
		{
			get
			{
				return this._danToc;
			}
			set
			{
				if ((this._danToc != value))
				{
					this._danToc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLop", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maLop
		{
			get
			{
				return this._maLop;
			}
			set
			{
				if ((this._maLop != value))
				{
					this._maLop = value;
				}
			}
		}
	}
	
	public partial class ThongTin_SelectAllResult
	{
		
		private string _tinh;
		
		private string _donViChuQuan;
		
		private string _tenTruong;
		
		private string _khoaHoc;
		
		private string _nganhHoc;
		
		private string _chuyenNganh;
		
		public ThongTin_SelectAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tinh", DbType="NVarChar(50)")]
		public string tinh
		{
			get
			{
				return this._tinh;
			}
			set
			{
				if ((this._tinh != value))
				{
					this._tinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_donViChuQuan", DbType="NVarChar(100)")]
		public string donViChuQuan
		{
			get
			{
				return this._donViChuQuan;
			}
			set
			{
				if ((this._donViChuQuan != value))
				{
					this._donViChuQuan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenTruong", DbType="NVarChar(100)")]
		public string tenTruong
		{
			get
			{
				return this._tenTruong;
			}
			set
			{
				if ((this._tenTruong != value))
				{
					this._tenTruong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khoaHoc", DbType="NVarChar(100)")]
		public string khoaHoc
		{
			get
			{
				return this._khoaHoc;
			}
			set
			{
				if ((this._khoaHoc != value))
				{
					this._khoaHoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nganhHoc", DbType="NVarChar(100)")]
		public string nganhHoc
		{
			get
			{
				return this._nganhHoc;
			}
			set
			{
				if ((this._nganhHoc != value))
				{
					this._nganhHoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chuyenNganh", DbType="NVarChar(100)")]
		public string chuyenNganh
		{
			get
			{
				return this._chuyenNganh;
			}
			set
			{
				if ((this._chuyenNganh != value))
				{
					this._chuyenNganh = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
